const data = [
  {
    id: 1,
    image: "../pics/pexels-realtoughcandycom-11035390.jpg",
    design: "NCD - DESIGN",
    name: "Mevine Thoda",
    officer: "Marketing Officer",
    post: "CEO - MARKETING",
    date: "Thoda department - Mar 4 - Aug 30, 2021",
    desc: "lorem",
  },
  {
    id: 2,
    image: "../pics/laravel.png",
    design: "DEFAULT - DESIGN",
    name: "Davie Luace",
    officer: "Chief Operating Officer",
    post: "Andriod App development",
    date: "Via Upwork - Mar 23 - Aug 30, 2021",
    desc: "When Management is so important",
  },
  {
    id: 3,
    image: "../pics/pexels-realtoughcandycom-11035390.jpg",
    design: "REACT WEBSITE - DESIGN",
    name: "Leanne Graham",
    officer: "Proactive didactic",
    post: "SALES MANAGER",
    date: "Via Twitter - Jan 2 - April , 2021",
    desc: "Multi-tiered zero tolerance productivity",
  },
  {
    id: 4,
    image: "../pics/pexels-realtoughcandycom-11035471.jpg",
    design: "PHP FullStack APP - DESIGN",
    name: "Clementine Bauch",
    officer: "Hoeger Mall",
    post: "CONTENT CREATOR",
    date: "Via Twitter - Jan 2 - April 6, 2021",
    desc: "Multi-layered client-server neural-net",
  },
  {
    id: 5,
    image: "../pics/PHP-Logo-Free-Download-PNG.png",
    design: "E-commerce Website - DESIGN",
    name: "Mrs. Dennis Schulist",
    officer: "South Christy",
    post: "SALES REP",
    date: "Via Twitter - Jan 2 - April 6, 2022",
    desc: "Configurable multimedia task-force",
  },
  {
    id: 6,
    image: "../pics/react-logo.jpg",
    design: "E-commerce Website - DESIGN",
    name: "Nicholas Runolfsdottir V",
    officer: "Dayna Park",
    post: "MEDICAL DOCTOR",
    date: "Via Fiverr - Feb 4 - April 18, 2022",
    desc: "Switchable contextually-based project",
  },
];
export default data;
